2025-04-18 02:16:55,412 - AgentFlow - INFO - Initializing MLOrchestratorAgent with model: model='gpt-4o-mini' llm_client=<google.adk.models.lite_llm.LiteLLMClient object at 0x7d3ee7a4a190>
2025-04-18 02:16:55,412 - AgentFlow - INFO - MLOrchestratorAgent initialized.
2025-04-18 02:16:55,413 - AgentFlow - INFO - --- Starting ML Copilot ADK Application ---
2025-04-18 02:16:55,413 - AgentFlow - INFO - Services initialized (InMemorySessionService, InMemoryArtifactService).
2025-04-18 02:16:55,413 - AgentFlow - INFO - Core FunctionTools available: ['code_execution_tool', 'logging_tool', 'human_approval_tool']
2025-04-18 02:16:55,413 - AgentFlow - INFO - AgentTool verified for: CodeGeneratorAgent
2025-04-18 02:16:55,413 - AgentFlow - INFO - AgentTool verified for: ImageAnalysisAgent
2025-04-18 02:16:55,413 - AgentFlow - ERROR - Failed to configure or wrap agent DataLoadingAgent: "DataLoadingAgent" object has no field "tools_map"
Traceback (most recent call last):
  File "/home/vatsal-patel/Documents/github/ml2/main.py", line 166, in main
    agent.tools_map = {t.name: t for t in current_agent_tools}
    ^^^^^^^^^^^^^^^
  File "/home/vatsal-patel/myenv/lib/python3.11/site-packages/pydantic/main.py", line 1000, in __setattr__
    elif (setattr_handler := self._setattr_handler(name, value)) is not None:
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vatsal-patel/myenv/lib/python3.11/site-packages/pydantic/main.py", line 1047, in _setattr_handler
    raise ValueError(f'"{cls.__name__}" object has no field "{name}"')
ValueError: "DataLoadingAgent" object has no field "tools_map"
